Update ablobs

diff --git a/ablobs b/ablobs
--- a/ablobs
+++ b/ablobs
@@ -6,15 +6,17 @@ foundc=0
 nfoundc=0
 _lib_dir="lib/"
 _vendor_lib_dir="vendor/lib/"
-_lib_list="/tmp/t-sh.txt"
-_missing="$(pwd)/t-sh-missing-files.txt"
+_lib_list="/tmp/ablobs"
+_missing="$(pwd)/ablobs_missing-files.txt"
 
-printf '  WARNING\n'
+rm -rf ${_lib_list} ${_tmp_lib_list}
+
+printf '\n  WARNING\n'
 printf "Make sure you are inside of '/system' dir\n"
 printf "If not, the script will be useless\n"
-printf '  WARNING\n'
+printf '  WARNING\n\n'
 read -p "Press any key to continue..." -s ask
-printf '\n'
+printf '\n\n'
 
 # Make loop for usage of 'break' to recursive exit
 while true
@@ -28,63 +30,16 @@ do
 		break
 	fi
 
-	# Check if 'objdump' is installed
-	if [ ! "$(which objdump)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'objdump'"
-		echo "  | Exiting from script!"
-		break
-	fi
-
-	# Check if 'find' is installed
-	if [ ! "$(which find)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'find'"
-		echo "  | Exiting from script!"
-		break
-	fi
-
-	# Check if 'grep' is installed
-	if [ ! "$(which grep)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'grep'"
-		echo "  | Exiting from script!"
-		break
-	fi
-
-	# Check if 'sort' is installed
-	if [ ! "$(which sort)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'sort'"
-		echo "  | Exiting from script!"
-		break
-	fi
-
-	# Check if 'uniq' is installed
-	if [ ! "$(which uniq)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'uniq'"
-		echo "  | Exiting from script!"
-		break
-	fi
-
-	# Check if 'sed' is installed
-	if [ ! "$(which sed)" ]
-	then
-		echo "  |"
-		echo "  | You will need to install 'sed'"
-		echo "  | Exiting from script!"
-		break
-	fi
+	# Check for tools installed
+	for TARGET in "objdump" "find" "grep" "sort" "uniq" "sed"
+	do
+		which ${TARGET} 1> /dev/null || { echo "  | ERROR: Install $TARGET before continuing."; break; }
+	done
 
 	echo "# Auto generated by Android Blob Utility Script" > ${_missing}
 
-	objdump -x $(find .) | grep NEEDED | sort | uniq | sed 's/  NEEDED               //' > ${_lib_list}
+	printf 'objdump working, see to other side \n'
+	objdump -x $(find . | grep -v /app | grep -v /priv-app | grep -v /usr | grep -v /tts | grep -v /etc | grep -v /media | grep -v /framework | grep -v /fonts | grep -v /addon.d | grep -v .txt | grep -v .bc | grep -v build.prop | grep -v keymaster | grep -v ablobs) | grep NEEDED | sort | uniq | cut -d " " -f 18 >> ${_lib_list}
 
 	while IFS= read -r _file
 	do
@@ -108,15 +63,16 @@ do
 		fi
 	done < "${_lib_list}"
 
-	printf 'Race results:\n'
-	printf '    Found: %s\n' "${foundc}"
-	printf '  Missing: %s\n' "${nfoundc}"
-	printf 'Missing files list saved on:\n'
-	printf '           %s\n' "${_missing}"
+	if [ "${nfoundc}" == "1" ]
+	then
+		a="$(cat ${_missing} | head -2 | tail -n 1 | cut -d " " -f 1)"
+	fi
+
+	printf '\nRace results:\n  %s/%s (%s) missing\n\n' "${nfoundc}" "${foundc}" "${a}"
+	printf 'The list with missing files saved on:\n  %s\n\n' "${_missing}"
 
 	# Exit at end
 	break
 done
 
-printf 'Thanks for use this script :)\n'
-printf 'Made by Caio99BR\n'
+printf 'Thanks for use this script - Written by Caio Oliveira aka Caio99BR\n'
